name: Piske Kubernetes Project

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-slim

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Project Files
        run: |
          echo "Project files:"
          ls -la

      - name: Check Kubernetes Files
        run: |
          echo "Kubernetes project:"
          ls -la
          echo "Checking folders:"
          ls -la mi-web
          ls -la notes-app

      - name: Workflow Successful
        run: echo "GitHub Actions workflow completed successfully!"
